name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14' 

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test || true 

    - name: Build Docker image
      run: |
        for i in {1..3}; do docker build -t my-node-app . && break || sleep 15; done

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Tag and Push Docker image
      run: |
        docker tag my-node-app:latest ${{ secrets.DOCKER_USERNAME }}/my-node-app:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/my-node-app:latest
